# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build  
    - run: git config user.email "developer@omarwais.com"
    - run: git config user.name "developeromarwais"
    #- run: git commit -am "Remodelling Directory"
    - name: Simple FTP deploy
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.0.1
      with:
        # FTP host
        ftp_host: 'ftp://185.201.10.126'
        # FTP username
        ftp_username: 'u771395700.developer.wais@gmail.com'
        # FTP password
        ftp_password: 'M2P>=BOc*o'
        # The local folder to copy
        local_source_dir: build
        # The remote folder
        dist_target_dir: /
